### ISSUE TITLE
more document about env.json

### ISSUE THREAD

**Issue by guoxj** [toby1991/sms-forwarder#2]
{
  "APP_NAME": "SMSForwarder",
  "APP_ENV": "develop",
  "APP_DEBUG": true,
  "APP_PORT": "80",
  "APP_LOCALE": "en",
  "APP_KEY": "YOUR-APP-KEY",   how to obtain a app-key

  "MONITOR_PORT": "8080",
  "MONITOR_USERNAME": "Totoval",
  "MONITOR_PASSWORD": "Passw0rd",

  "DB_CONNECTION": "mysql",
  "DB_HOST": "127.0.0.1",
  "DB_PORT": "3306",
  "DB_DATABASE": "YOUR-DATABASE-NAME",
  "DB_USERNAME": "YOUR-DATABASE-USER",
  "DB_PASSWORD": "YOUR-DATABASE-USER-PASSWORD",
  "DB_PREFIX": "prefix_",

  "CACHE_DRIVER": "memory",
  "REDIS_HOST": "127.0.0.1",
  "REDIS_PORT": "6379",
  "REDIS_PASSWORD": "",
  "REDIS_DB": 0,
  "REDIS_CACHE_DB": 1,

  "AUTH_SIGN_KEY": "YOUR-AUTH-SIGN-KEY",

  "QUEUE_CONNECTION": "nsq",
  "QUEUE_NSQD_TCP_HOST": "127.0.0.1",
  "QUEUE_NSQD_TCP_PORT": "4150",
  "QUEUE_NSQLOOKUPD_HTTP_HOST": "http://127.0.0.1",
  "QUEUE_NSQLOOKUPD_HTTP_PORT": "4161",
  "QUEUE_MAX_IN_FLIGHT": "50",

  "PUSHOVER_TOKEN": " ",
  "PUSHOVER_USER": " ",
  "PUSHOVER_DEVICE": " "
}

can you please describe this env.json in details?
like how to obtain APP_KEY?
and which  fields are required？

**Comment by toby1991** [comment]
Oh I'm sorry for the confusing which made by the `example.env.json`. I'm updating a new version of that, that would solve all your question about the `env.json`.

For `APP_KEY `, you could jus random a string for that.
