### ISSUE TITLE
not working for sms body lenth more than 7 characters

### ISSUE THREAD

**Issue by guoxj** [toby1991/sms-forwarder#3]
如果短信息很短，他可以接收到并且推送到pushover
如果短信息长度比较长，则无法推送。
举例来说：
接收到短信内容为how，表现正常
接收到短信内容为hellogod，接收到推送内容为hellogo
接收到短信内容为Your Apple ID Verification Code is：234246 ，则收不到推送信息。

If the SMS body is short, it can receive it and push it to pushover.
If the SMS body length is long, it cannot be pushed.
for example:
Received SMS content is "how", normal performance
Received the message content is "hellogo", received the push content is "hellogo"
Received the message content is "Your Apple ID Verification Code is: 234246", it totaly not working.

**Comment by toby1991** [comment]
Please provide the `RAW CONTENT` of the sms which will be provided in logs, or in the `sms.csv` files in the folder.

**Comment by toby1991** [comment]
For long sms, the app will separate it into multiple sms, because of the protocol. But all the children of this sms will be send by the notifier.

**Comment by toby1991** [comment]
Seems that `hellogod` has some problem, But I've received the last sms.

![IMG_3282](https://user-images.githubusercontent.com/5897356/69008803-913bb400-0989-11ea-807f-f59a0439b0d0.jpg)
![IMG_3281](https://user-images.githubusercontent.com/5897356/69008804-939e0e00-0989-11ea-8cad-56723a1c4d28.jpg)

**Comment by toby1991** [comment]
Fixed by: commit https://github.com/toby1991/sms-forwarder/commit/f8e4f9a9850f043c42ada95d1dc1ec9107074003

Issue closed, feel free to reopen it if there's another issue related to this one.
