### ISSUE TITLE
Pannic error log, can you kindly check it

### ISSUE THREAD

**Issue by guoxj** [toby1991/sms-forwarder#5]
INFO[2020-01-06T18:35:36+08:00] Incoming data                                 data="OK\r\n\r\n+CPMS: \"SM_P\",2,50,\"SM_P\",2,50,\"SM_P\",2,50\r\n\r\nOK\r\n"
INFO[2020-01-06T18:35:36+08:00] sms amount                                    amount=2 max=50
PANI[2020-01-06T18:35:36+08:00] EOF                                          
panic: (*logrus.Entry) (0x7d05e0,0x1912f40)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x1afe080, 0x187da20, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2d8
github.com/sirupsen/logrus.(*Entry).Log(0x1912000, 0x0, 0x1903ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0x88
github.com/sirupsen/logrus.(*Logger).Log(0x1afe080, 0x0, 0x1903ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x70
github.com/totoval/framework/logs.Println(0x0, 0x733fc8, 0x1878018, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/logs/log.go:42 +0x408
github.com/totoval/framework/helpers/log.Panic(0x733fc8, 0x1878018, 0x0, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/helpers/log/helpers.go:51 +0x44
totoval/app/logics/phone.(*phone).Listen(0x19a0240)
	/home/pi/Project/2/app/logics/phone/phone.go:47 +0x154
totoval/app/console/commands.(*SmsReader).Handler(0xe30d24, 0x1bc6910, 0x0, 0x0)
	/home/pi/Project/2/app/console/commands/sms_reader.go:59 +0x284
github.com/totoval/framework/cmd.List.func1(0x1b94210, 0x0, 0x1b94210)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/cmd/manager.go:79 +0x140
github.com/urfave/cli.HandleAction(0x70f9d0, 0x850948, 0x1b94210, 0x1891700, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xac
github.com/urfave/cli.Command.Run(0x7e8ab4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x801806, 0x37, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x760
github.com/urfave/cli.(*App).Run(0x1862700, 0x187c060, 0x3, 0x4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x494
main.cliServe()
	/home/pi/Project/2/artisan.go:67 +0x124
main.main()
	/home/pi/Project/2/artisan.go:39 +0x14
exit status 2

**Comment by toby1991** [comment]
`PANI[2020-01-06T18:35:36+08:00] EOF`
This error was caused by your chip - `EOF`.

Check your chip whether it is gone while reading sms.

**Comment by guoxj** [comment]
INFO[2020-01-07T13:55:41+08:00] Incoming data                                 data="OK\r\n\r\n+CPMS: \"SM_P\",8,10,\"SM_P\",8,10,\"SM_P\",8,10\r\n\r\nOK\r\n"
INFO[2020-01-07T13:55:41+08:00] sms amount                                    amount=8 max=10
PANI[2020-01-07T13:55:41+08:00] EOF                                          
panic: (*logrus.Entry) (0x7d05e0,0x306f580)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x32ee040, 0x34559c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2d8
github.com/sirupsen/logrus.(*Entry).Log(0x306e100, 0x0, 0x3101ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0x88
github.com/sirupsen/logrus.(*Logger).Log(0x32ee040, 0x0, 0x3101ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x70
github.com/totoval/framework/logs.Println(0x0, 0x733fc8, 0x3078018, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/logs/log.go:42 +0x408
github.com/totoval/framework/helpers/log.Panic(0x733fc8, 0x3078018, 0x0, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/helpers/log/helpers.go:51 +0x44
totoval/app/logics/phone.(*phone).Listen(0x307cde0)
	/home/pi/Project/6/app/logics/phone/phone.go:47 +0x154
totoval/app/console/commands.(*SmsReader).Handler(0xe30d24, 0x33cc668, 0x0, 0x0)
	/home/pi/Project/6/app/console/commands/sms_reader.go:59 +0x284
github.com/totoval/framework/cmd.List.func1(0x3396210, 0x0, 0x3396210)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/cmd/manager.go:79 +0x140
github.com/urfave/cli.HandleAction(0x70f9d0, 0x850948, 0x3396210, 0x3184c00, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xac
github.com/urfave/cli.Command.Run(0x7e8ab4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x801806, 0x37, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x760
github.com/urfave/cli.(*App).Run(0x30607e0, 0x307c060, 0x3, 0x4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x494
main.cliServe()
	/home/pi/Project/6/artisan.go:67 +0x124
main.main()
	/home/pi/Project/6/artisan.go:39 +0x14
exit status 2

**Comment by guoxj** [comment]
no, the chip is ok

**Comment by guoxj** [comment]
Sometime it crash only on the first time it started

pi@raspberrypi:~/Project/1 $ go run artisan.go sms:read /dev/ttyUSB0
INFO[2020-01-08T15:20:57+08:00] Send Bytes                                    bytes="ATE0\r\n" length=6
INFO[2020-01-08T15:20:57+08:00] Send Bytes                                    bytes="AT+CMEE=1\r\n" length=11
INFO[2020-01-08T15:20:57+08:00] Send Bytes                                    bytes="AT+CMGF=0\r\n" length=11
INFO[2020-01-08T15:20:57+08:00] Listening                                     com_port=/dev/ttyUSB0
PANI[2020-01-08T15:21:05+08:00] EOF                                          
panic: (*logrus.Entry) (0x7d05e0,0x2484600)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x2700040, 0x28bba60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2d8
github.com/sirupsen/logrus.(*Entry).Log(0x2484200, 0x0, 0x2887ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0x88
github.com/sirupsen/logrus.(*Logger).Log(0x2700040, 0x0, 0x2887ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x70
github.com/totoval/framework/logs.Println(0x0, 0x733fc8, 0x2478018, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/logs/log.go:42 +0x408
github.com/totoval/framework/helpers/log.Panic(0x733fc8, 0x2478018, 0x0, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/helpers/log/helpers.go:51 +0x44
totoval/app/logics/phone.(*phone).Listen(0x28bbaa0)
	/home/pi/Project/1/app/logics/phone/phone.go:47 +0x154
totoval/app/console/commands.(*SmsReader).Handler(0xe30d24, 0x27c6650, 0x0, 0x0)
	/home/pi/Project/1/app/console/commands/sms_reader.go:59 +0x284
github.com/totoval/framework/cmd.List.func1(0x2794210, 0x0, 0x2794210)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/cmd/manager.go:79 +0x140
github.com/urfave/cli.HandleAction(0x70f9d0, 0x850948, 0x2794210, 0x25aa800, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xac
github.com/urfave/cli.Command.Run(0x7e8ab4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x801806, 0x37, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x760
github.com/urfave/cli.(*App).Run(0x2462700, 0x247c060, 0x3, 0x4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x494
main.cliServe()
	/home/pi/Project/1/artisan.go:67 +0x124
main.main()
	/home/pi/Project/1/artisan.go:39 +0x14
exit status 2


when start again,it will work properly.

**Comment by guoxj** [comment]
PANI[2020-01-10T09:22:56+08:00] EOF                                          
panic: (*logrus.Entry) (0x7d05e0,0x2c84200)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0x2efe080, 0x2dc8040, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:239 +0x2d8
github.com/sirupsen/logrus.(*Entry).Log(0x2c841c0, 0x0, 0x2c45ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/entry.go:268 +0x88
github.com/sirupsen/logrus.(*Logger).Log(0x2efe080, 0x0, 0x2c45ba4, 0x1, 0x1)
	/home/pi/go/pkg/mod/github.com/sirupsen/logrus@v1.4.2/logger.go:192 +0x70
github.com/totoval/framework/logs.Println(0x0, 0x733fc8, 0x2c78018, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/logs/log.go:42 +0x408
github.com/totoval/framework/helpers/log.Panic(0x733fc8, 0x2c78018, 0x0, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/helpers/log/helpers.go:51 +0x44
totoval/app/logics/phone.(*phone).Listen(0x2c7d040)
	/home/pi/Project/2/app/logics/phone/phone.go:47 +0x154
totoval/app/console/commands.(*SmsReader).Handler(0xe30d24, 0x309a7c8, 0x0, 0x0)
	/home/pi/Project/2/app/console/commands/sms_reader.go:59 +0x284
github.com/totoval/framework/cmd.List.func1(0x2f94210, 0x0, 0x2f94210)
	/home/pi/go/pkg/mod/github.com/totoval/framework@v0.11.4/cmd/manager.go:79 +0x140
github.com/urfave/cli.HandleAction(0x70f9d0, 0x850948, 0x2f94210, 0x2c91600, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xac
github.com/urfave/cli.Command.Run(0x7e8ab4, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x801806, 0x37, 0x0, ...)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x760
github.com/urfave/cli.(*App).Run(0x2c62700, 0x2c7c060, 0x3, 0x4, 0x0, 0x0)
	/home/pi/go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x494
main.cliServe()
	/home/pi/Project/2/artisan.go:67 +0x124
main.main()
	/home/pi/Project/2/artisan.go:39 +0x14
exit status 2

**Comment by guoxj** [comment]
This crash persists and SMS can be received normally after re-running the APP.

**Comment by guoxj** [comment]
can we have a private conversation?

**Comment by guoxj** [comment]
I comment the line  /home/pi/Project/1/app/logics/phone/phone.go:47 +0x154
it shows:
ATE0 AT+CMEE=1 AT+CMGF=0 OK OK OK |ATE0 AT+CMEE=1 AT+CMGF=0 OK OK OK

**Comment by toby1991** [comment]
Fixed @guoxj, Thank you.
